# Generated by Django 6.0.2 on 2026-03-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
