# Generated by Django 6.0.2 on 2026-03-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
