# Generated by Django 6.0.2 on 2026-03-07 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0002_expenses_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='patner',
            new_name='partner',
        ),
    ]
