# Generated by Django 6.0.2 on 2026-03-07 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0004_alter_expenses_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='user_id',
            new_name='user',
        ),
    ]
