# Generated by Django 6.0.2 on 2026-03-08 06:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0005_rename_user_id_expenses_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='date',
        ),
        migrations.AddField(
            model_name='expenses',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenses',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
